name: Docker Image CI

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Git Semantic Version
        uses: PaulHatch/semantic-version@v4.0.3
        with:
          major_pattern: 'major:'
          minor_pattern: 'feature:'
          format: '${major}.${minor}.${patch}-${increment}'
        id: version

      - name: Docker login
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          NEW_VERSION: ${{ steps.version.outputs.version }}
        run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
          echo "New version: $NEW_VERSION !!!! major"

      - name: Building Docker Image
        env:
          NEW_VERSION: ${{ steps.version.outputs.version }}
        run: |
          docker build -t luisrmunoz/docker-graphql:$NEW_VERSION .
          docker build -t luisrmunoz/docker-graphql:latest .

      - name: Pushing Docker Image
        env:
          NEW_VERSION: ${{ steps.version.outputs.version }}
        run: |
          docker push luisrmunoz/docker-graphql:$NEW_VERSION
          docker push luisrmunoz/docker-graphql:latest

    # - name: Build the Docker image
    #   run: docker build . --file Dockerfile --tag my-image-name:$(date +%s
